"""initial schema

Revision ID: 5888c6c6f234
Revises: 
Create Date: 2026-06-14 19:42:31.476940

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5888c6c6f234'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_state',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funpay_node_id', sa.Integer(), nullable=True),
    sa.Column('funpay_lot_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('game', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('delivery_template', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_extension', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funpay_lot_id')
    )
    op.create_index('ix_lots_title', 'lots', ['title'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.Text(), nullable=False),
    sa.Column('password_enc', sa.LargeBinary(), nullable=False),
    sa.Column('steam_id', sa.Text(), nullable=True),
    sa.Column('shared_secret_enc', sa.LargeBinary(), nullable=False),
    sa.Column('identity_secret_enc', sa.LargeBinary(), nullable=False),
    sa.Column('revocation_code_enc', sa.LargeBinary(), nullable=True),
    sa.Column('device_id', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index('ix_accounts_lot_id_status', ['lot_id', 'status'], unique=False)

    op.create_table('rentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('funpay_order_id', sa.Text(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('buyer_username', sa.Text(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('warned', sa.Boolean(), nullable=False),
    sa.Column('extended_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funpay_order_id')
    )
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.create_index('ix_rentals_status_expires_at', ['status', 'expires_at'], unique=False)

    op.create_table('extensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rental_id', sa.Integer(), nullable=False),
    sa.Column('minutes_added', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('funpay_order_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funpay_order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extensions')
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.drop_index('ix_rentals_status_expires_at')

    op.drop_table('rentals')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_accounts_lot_id_status')

    op.drop_table('accounts')
    op.drop_table('lots')
    op.drop_table('bot_state')
    # ### end Alembic commands ###